version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inovati
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: npm run dev
    volumes:
      - ./backend:/app
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=postgresql://root:root@db:5432/inovati
    depends_on:
      - db
  frontend:
    build: .
    command: npm run dev
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
volumes:
  pgdata:
